/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import static StudentRegister.StudentRegister.students;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import static model.FileManager.registerFile;

/**
 *
 * @author RobertTerolLacasta
 */
public class FindStudent extends javax.swing.JFrame {

    /**
     * Creates new form RemoveStudent
     */
    public FindStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtDNI = new javax.swing.JTextField();
        jBttnOK = new javax.swing.JButton();
        jBttnFind = new javax.swing.JButton();
        jLblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLblTitle.setText("Find student");
        jLblTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLblTitle.setPreferredSize(new java.awt.Dimension(87, 36));

        jLabel1.setText("DNI of the student you want to search:");

        jTxtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDNIActionPerformed(evt);
            }
        });

        jBttnOK.setText("OK");
        jBttnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnOKActionPerformed(evt);
            }
        });

        jBttnFind.setText("Find");
        jBttnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnFindActionPerformed(evt);
            }
        });

        jLblMessage.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBttnOK)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtDNI, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jBttnFind)
                    .addComponent(jLblMessage))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBttnFind)
                .addGap(18, 18, 18)
                .addComponent(jLblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jBttnOK)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDNIActionPerformed

    private void jBttnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnFindActionPerformed
        for (var student : students) {
            if (jTxtDNI.getText().equalsIgnoreCase(student.getDni())) {
                jLblMessage.setText(student.toString());
                
            }
                else{
                jLblMessage.setText("Estudiante no encontrado");
            }
        }
            
    }//GEN-LAST:event_jBttnFindActionPerformed

    private void jBttnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnOKActionPerformed
        this.setVisible(false);
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBttnOKActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnFind;
    private javax.swing.JButton jBttnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblMessage;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JTextField jTxtDNI;
    // End of variables declaration//GEN-END:variables
}
