/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import static StudentRegister.StudentRegister.students;

/**
 *
 * @author RobertTerolLacasta
 */
public class ShowStudents extends javax.swing.JFrame {

    /**
     * Creates new form ShowStudents
     */
    public ShowStudents() {
        initComponents();
        setStudentsList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitle = new javax.swing.JLabel();
        jLblStudentList = new javax.swing.JLabel();
        jBttnOK = new javax.swing.JButton();
        jBttnNextPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLblTitle.setText("Students List");
        jLblTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLblTitle.setPreferredSize(new java.awt.Dimension(87, 36));

        jLblStudentList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLblStudentList.setText("jLabel1");
        jLblStudentList.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jBttnOK.setText("OK");
        jBttnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnOKActionPerformed(evt);
            }
        });

        jBttnNextPage.setText("Next page");
        jBttnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnNextPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblStudentList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(376, Short.MAX_VALUE)
                        .addComponent(jBttnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBttnOK)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblStudentList, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBttnOK)
                    .addComponent(jBttnNextPage))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnOKActionPerformed
        this.setVisible(false);
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBttnOKActionPerformed

    private void jBttnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnNextPageActionPerformed
        int line = 0;
        
        jLblStudentList.setText("<html>");
        
        for (var student : students) {
            
            line = line+1;
            jLblStudentList.setText(jLblStudentList.getText() + line + ": " + student.toString() + "<br>");
            
            
        }
        jLblStudentList.setText(jLblStudentList.getText() + "</html>");
        
    }//GEN-LAST:event_jBttnNextPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowStudents().setVisible(true);
            }
        });
    }
    
    
    public void setStudentsList(){
        int line = 0;
        
        jLblStudentList.setText("<html>");
        
        for (var student : students) {
            
            line = line+1;
            jLblStudentList.setText(jLblStudentList.getText() + line + ": " + student.toString() + "<br>");
            
            
        }
        jLblStudentList.setText(jLblStudentList.getText() + "</html>");
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnNextPage;
    private javax.swing.JButton jBttnOK;
    private javax.swing.JLabel jLblStudentList;
    private javax.swing.JLabel jLblTitle;
    // End of variables declaration//GEN-END:variables
}
