package model;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import model.ShowStudents;
import model.AddStudent;

/**
 *
 * @author RobertTerolLacasta
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBttnShowStudents = new javax.swing.JButton();
        jBttnAddStudent = new javax.swing.JButton();
        jBttnDeleteStudent = new javax.swing.JButton();
        jBttnSearchStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBttnShowStudents.setText("Show student list");
        jBttnShowStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnShowStudentsActionPerformed(evt);
            }
        });

        jBttnAddStudent.setText("Add new Student");
        jBttnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAddStudentActionPerformed(evt);
            }
        });

        jBttnDeleteStudent.setText("Delete student");
        jBttnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnDeleteStudentActionPerformed(evt);
            }
        });

        jBttnSearchStudent.setText("Search student");
        jBttnSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSearchStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBttnAddStudent)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jBttnDeleteStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBttnShowStudents, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBttnSearchStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jBttnAddStudent)
                .addGap(18, 18, 18)
                .addComponent(jBttnShowStudents)
                .addGap(18, 18, 18)
                .addComponent(jBttnDeleteStudent)
                .addGap(18, 18, 18)
                .addComponent(jBttnSearchStudent)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAddStudentActionPerformed
        new AddStudent().setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jBttnAddStudentActionPerformed

    private void jBttnShowStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnShowStudentsActionPerformed
        new ShowStudents().setVisible(true);
        this.setVisible(false);
        dispose();
                   
    }//GEN-LAST:event_jBttnShowStudentsActionPerformed

    private void jBttnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnDeleteStudentActionPerformed
        new RemoveStudent().setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jBttnDeleteStudentActionPerformed

    private void jBttnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSearchStudentActionPerformed
        new FindStudent().setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jBttnSearchStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu menu = new Menu();
                menu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAddStudent;
    private javax.swing.JButton jBttnDeleteStudent;
    private javax.swing.JButton jBttnSearchStudent;
    private javax.swing.JButton jBttnShowStudents;
    // End of variables declaration//GEN-END:variables
}
